# .github/workflows/ci.yml
name: CI Workflow

on:
  push:
    paths:
      - 'VTI-frontend/**'
      - 'VTI-backend/**'
  pull_request:
    paths:
      - 'VTI-frontend/**'
      - 'VTI-backend/**'
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend CI
    needs: backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        working-directory: VTI-frontend
        run: npm install

      - name: Run lint
        working-directory: VTI-frontend
        run: npm run lint

      - name: Build project
        working-directory: VTI-frontend
        run: npm run build --prod

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run:  |
          OUTPUT=$(npx vercel deploy VTI-frontend/ --yes  --token=$VERCEL_TOKEN)
          echo "$OUTPUT"
          DEPLOY_URL=$(echo "$OUTPUT" | grep -oP 'https?://\S+' | head -n 1)
          echo "Deployment URL: $DEPLOY_URL"
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Alias Deployment to Custom Domain
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -z "$DEPLOY_URL" ]; then
            echo "No deployment URL found!"
            exit 1
          fi
          npx vercel alias $DEPLOY_URL vti-frontend.vercel.app --token=$VERCEL_TOKEN
    
      - name: Run Cypress tests
        working-directory: VTI-frontend
        env:
          BASE_URL: ${{ env.DEPLOY_URL }} 
        run: |
          npm install cypress
          echo "BASE_URL is: $BASE_URL"
          npx cypress run --spec "cypress/e2e/api_check.cy.js"
          npx cypress run

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: VTI_database
          MYSQL_USER: VTI
          MYSQL_PASSWORD: VTI-database1234
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Build Docker Images
        run: |
          docker build -t mysql-database .
          docker build -t vti-backend -f Dockerfile .
    
      - name: Start MySQL Container
        run: |
          docker network create vti-network || true
          docker run -d --name mysql-database --network vti-network \
            -e MYSQL_DATABASE=VTI_database \
            -e MYSQL_USER=VTI \
            -e MYSQL_PASSWORD=VTI-database1234 \
            -e MYSQL_ROOT_PASSWORD=rootpassword \
            mysql:latest
          echo "Waiting for MySQL container to be ready..."
          until docker exec mysql-database mysqladmin ping --silent; do
            sleep 2
          done
          echo "MySQL is ready."
    
      - name: Run Tests in Backend Container
        run: |
          docker run --rm --name vti-backend --network vti-network \
            -e SPRING_PROFILES_ACTIVE=test \
            vti-backend mvn test
  
      - name: SonarCloud Scan
        working-directory: VTI-backend
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=I485354_VTI
  
      - name: Run Backend Container
        run: |
          docker run -d --name vti-backend --network vti-network -p 8080:8080 vti-backend
          echo "Backend container is running."

